# PLATFORMS WITH SERVICES YOU CAN ACCESS THE OPENAI MODELS

# PLATFORM OPENAI COM 
# HTTPS://AI.GOOGLE.DEV/

# LEARN ALL THE MODELS AND HOW IT GONNA IMPLEMENT
# MODELS SUCH AS 
# GEMINI MODELS 
# MULTIMEDIA MODELS 
# EMMBEDINGMODELS 

# PLATFORM CAN PROVIDE THE ACCESS TO THE MODELS

# MODELS USED TO GERNATE THE RESPOSNE AND ANSWERS

# FRIST THING FRIST 

# CREATE AN AGENT , GENRATE AN API KEY FROM AI.GOOGLE.DEV , 
#CREATE AN ENVIORMENT WHERE THE PROJECT IS GONNA CREATE 
# -----------IN FILE THERE HAS TO BE .ENV FILE AND APP.PY AND REQUIREMENTS.PY -- MANDATORY

PIP INSATLL OPENAI
PIP...REQUESTS
PIP...FLASK
PIP....FASTAPI
PIP INSATLL PYTHON-DOTENV
PIP INSTALL google-generativeai==0.5.2
pip show google-generativeai==0.5.2

